### ISSUE TITLE
Create React App

### ISSUE THREAD

**Issue by cynepton** [BuildForSDGCohort2/Team-085-Frontend#2]
Run create-react-app and setup the starter files for the Frontend Application. React is the framework of choice as  we are required to use at least one open source facebook software in this project.

**Comment by mayowa-ola** [comment]
Alright...You are creating the react repo right?

**Comment by cynepton** [comment]
Yes, I am. I'll be setting up the application so you can begin working. I want to ensure we are all aware of exactly what each person is working on at every point in time. I'll talk more on this on the slack channel. Just know for now that before you take on a task, an issue must have been created for it first and must be assigned to you

**Comment by mayowa-ola** [comment]
Alright....copy that
